# 简化版资源配置（按资源填写），先定好格式再调整代码适配
# 目标：每个资源清晰列出总核数、每个软件的二进制路径与使用核心数、可选环境变量/MPI 命令

resources:
  - name: local_workstation
    type: local
    cores: 8                     # 资源最大核心数（用于容量/并发控制）
    software:
      atlas:
        path: "/Users/chenys/project/TB-OFDFT/phase2/soft/atlas_gcc/src/atlas_mpi.x"
        cores: 1                 # 单个任务为 ATLAS 分配的核心数
        env:
          OMP_NUM_THREADS: "1"
      qe:
        path: "/Users/chenys/project/TB-OFDFT/phase2/soft/q-e-qe-7.3.1/build/bin/pw.x"
        cores: 1                 # 单个任务为 QE 分配的核心数（>1 则启用 MPI）
        mpi: "mpirun"            # 可选：MPI 命令
        env:
          OMP_NUM_THREADS: "1"

  - name: server_6101
    type: remote
    host: "6101"
    user: "chenys"
    workdir: "~/atlas_qe_jobs"
    transfer:
      pull_all: true
    cores: 72
    software:
      atlas:
        path: "/home/chenys/soft/atlas_gcc/src/atlas_mpi.x"
        cores: 1
        env:
          OMP_NUM_THREADS: "1"
      qe:
        path: "/home/chenys/soft/q-e-qe-7.3.1/build/bin/pw.x"
        cores: 4
        mpi: "mpirun"
        env:
          OMP_NUM_THREADS: "1"

# 全局调度与监控（最小必要项）
scheduler:
  max_parallel: 2               # 同时运行的任务数量上限（全局）
  poll_interval: 2              # 轮询间隔（秒）

timeouts:
  default: 220                   # 软超时（秒），用于非阻塞轮询
  atlas: 1800                   # 可选：阻塞路径或软件特定超时
  qe: 7200

# 简单策略（可选）：多核 QE 优先远端、ATLAS 优先本地
policy:
  prefer:
    atlas: local
    qe_multicore: remote
