# Realistic GaAs system configuration based on actual calculations
# Path example: /Users/chenys/project/TB-OFDFT/phase2/project/ncpp_density/eos/
system: "GaAs"
elements: ["As", "Ga"]  # Order matches real calculation
structures: ["zinc_blende"]  # GaAs has zinc blende structure
volume_range: [0.94, 1.06]  # ±6% volume variation for EOS
volume_points: 11

atlas:
  functionals: ["kedf801"]  # Real example uses 801
  gap: [0.20]  # Real GAP parameter
  # Real pseudopotential files from the calculation
  pseudopotential_sets:
    - name: "lda_lpp_density"
      files: ["as.lda.lpp.lpp_density.UPF", "ga.lda.lpp.lpp_density.UPF"]
    - name: "lda_nlpp"
      files: ["as.lda.nlpp.UPF", "ga.lda.nlpp.UPF"]
    - name: "lda_upf"
      files: ["as.lda.upf", "ga.lda.upf"]

qe:
  configurations: ["lda_ecut60"]  # Real example uses ecut=60
  k_points: [[9,9,9]]  # Real example uses 9x9x9
  # Real QE parameters
  parameters:
    ecutwfc: 60
    ecutrho: 240  # 4x ecutwfc as in real example
    xc_functional: "LDA"  # Real example uses PZ (LDA)
    conv_thr: 1.0e-7
    electron_maxstep: 500
    mixing_beta: 0.2
    mixing_mode: "local-TF"
  # Real pseudopotential files
  pseudopotential_sets:
    - name: "lda_lpp_density"
      files: ["as.lda.lpp.lpp_density.UPF", "ga.lda.lpp.lpp_density.UPF"]
    - name: "lda_nlpp"
      files: ["as.lda.lpp.nlpp_density.UPF", "ga.lda.lpp.nlpp_density.UPF"]