# Single element system configuration example (Mg)
system: "Mg"
elements: ["Mg"]
structures: ["fcc", "bcc"]
volume_range: [0.8, 1.2]
volume_points: 11

atlas:
  functionals: ["kedf701", "kedf801"]
  gap: [0.20, 0.25]
  pseudopotentials: ["Mg_lda.recpot", "Mg_pbe.recpot"]

qe:
  configurations: ["ncpp_ecut60", "paw_ecut80"]
  k_points: [[10,10,10], [12,12,12]]
  pseudopotentials: ["Mg.ncpp.upf", "Mg.paw.upf"]