# Multi-element system configuration example (MgAl)
system: "MgAl"
elements: ["Mg", "Al"]
structures: ["fcc", "bcc", "l12"]
volume_range: [0.8, 1.2]
volume_points: 11

atlas:
  functionals: ["kedf701", "kedf801"]
  gap: [0.20, 0.25]
  # Pseudopotential combinations for multi-element systems
  pseudopotential_sets:
    - name: "lda_combo"
      files: ["Mg_lda.recpot", "Al_lda.recpot"]
    - name: "pbe_combo"
      files: ["Mg_pbe.recpot", "Al_pbe.recpot"]
    - name: "mixed_combo"
      files: ["Mg_lda.recpot", "Al_pbe.recpot"]

qe:
  configurations: ["ncpp_ecut60", "paw_ecut80"]
  k_points: [[10,10,10], [12,12,12]]
  # QE pseudopotential combinations
  pseudopotential_sets:
    - name: "ncpp_lda"
      files: ["Mg.ncpp.lda.upf", "Al.ncpp.lda.upf"]
    - name: "paw_pbe"
      files: ["Mg.paw.pbe.upf", "Al.paw.pbe.upf"]
    - name: "mixed_precision"
      files: ["Mg.ncpp.upf", "Al.paw.upf"]